name: CI

on:
# disabling this as the deploy-ai-monster.yml now triggers checks on pushes to main
#  push:
#    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
